[2023-03-21T10:08:31.527+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T10:08:02.026282+00:00 [queued]>
[2023-03-21T10:08:31.566+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T10:08:02.026282+00:00 [queued]>
[2023-03-21T10:08:31.567+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T10:08:31.568+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-21T10:08:31.568+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T10:08:31.629+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster> on 2023-03-21 10:08:02.026282+00:00
[2023-03-21T10:08:31.653+0000] {standard_task_runner.py:55} INFO - Started process 28634 to run task
[2023-03-21T10:08:31.678+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_masterdag', 'create_dataproc_cluster', 'manual__2023-03-21T10:08:02.026282+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/project_master_dags.py', '--cfg-path', '/tmp/tmpsj8vq7bx']
[2023-03-21T10:08:31.689+0000] {standard_task_runner.py:83} INFO - Job 283: Subtask create_dataproc_cluster
[2023-03-21T10:08:31.759+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-21T10:08:32.002+0000] {task_command.py:388} INFO - Running <TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T10:08:02.026282+00:00 [running]> on host 796cac132c25
[2023-03-21T10:08:32.359+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_masterdag
AIRFLOW_CTX_TASK_ID=create_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T10:08:02.026282+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T10:08:02.026282+00:00
[2023-03-21T10:08:32.362+0000] {dataproc.py:601} INFO - Creating cluster: my-dataproc-cluster
[2023-03-21T10:08:32.364+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-21T10:10:57.992+0000] {dataproc.py:614} INFO - Cluster created.
[2023-03-21T10:10:58.059+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_masterdag, task_id=create_dataproc_cluster, execution_date=20230321T100802, start_date=20230321T100831, end_date=20230321T101058
[2023-03-21T10:10:58.167+0000] {local_task_job.py:212} INFO - Task exited with return code 0
