[2023-03-21T10:22:10.707+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T10:08:02.026282+00:00 [queued]>
[2023-03-21T10:22:10.721+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T10:08:02.026282+00:00 [queued]>
[2023-03-21T10:22:10.722+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T10:22:10.722+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 3
[2023-03-21T10:22:10.723+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T10:22:10.744+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster> on 2023-03-21 10:08:02.026282+00:00
[2023-03-21T10:22:10.755+0000] {standard_task_runner.py:55} INFO - Started process 29329 to run task
[2023-03-21T10:22:10.763+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_masterdag', 'create_dataproc_cluster', 'manual__2023-03-21T10:08:02.026282+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/project_master_dags.py', '--cfg-path', '/tmp/tmpbobqjx4g']
[2023-03-21T10:22:10.768+0000] {standard_task_runner.py:83} INFO - Job 288: Subtask create_dataproc_cluster
[2023-03-21T10:22:10.810+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-21T10:22:10.937+0000] {task_command.py:388} INFO - Running <TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T10:08:02.026282+00:00 [running]> on host 796cac132c25
[2023-03-21T10:22:11.171+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_masterdag
AIRFLOW_CTX_TASK_ID=create_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T10:08:02.026282+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T10:08:02.026282+00:00
[2023-03-21T10:22:11.174+0000] {dataproc.py:601} INFO - Creating cluster: my-dataproc-cluster
[2023-03-21T10:22:11.176+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-21T10:25:08.892+0000] {dataproc.py:614} INFO - Cluster created.
[2023-03-21T10:25:08.956+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_masterdag, task_id=create_dataproc_cluster, execution_date=20230321T100802, start_date=20230321T102210, end_date=20230321T102508
[2023-03-21T10:25:09.017+0000] {local_task_job.py:212} INFO - Task exited with return code 0
