[2023-03-19T13:03:33.898+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_bq_data.create_dataproc_cluster manual__2023-03-18T00:22:20.257510+00:00 [queued]>
[2023-03-19T13:03:33.930+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_bq_data.create_dataproc_cluster manual__2023-03-18T00:22:20.257510+00:00 [queued]>
[2023-03-19T13:03:33.931+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-19T13:03:33.931+0000] {taskinstance.py:1283} INFO - Starting attempt 52 of 53
[2023-03-19T13:03:33.932+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-19T13:03:33.980+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster> on 2023-03-18 00:22:20.257510+00:00
[2023-03-19T13:03:33.998+0000] {standard_task_runner.py:55} INFO - Started process 1862 to run task
[2023-03-19T13:03:34.004+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'transform_bq_data', 'create_dataproc_cluster', 'manual__2023-03-18T00:22:20.257510+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/p_spark_processing.py', '--cfg-path', '/tmp/tmptehwu5rl']
[2023-03-19T13:03:34.032+0000] {standard_task_runner.py:83} INFO - Job 136: Subtask create_dataproc_cluster
[2023-03-19T13:03:34.096+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-19T13:03:34.292+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_bq_data.create_dataproc_cluster manual__2023-03-18T00:22:20.257510+00:00 [running]> on host f1b65b8eb897
[2023-03-19T13:03:34.527+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_bq_data
AIRFLOW_CTX_TASK_ID=create_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T00:22:20.257510+00:00
AIRFLOW_CTX_TRY_NUMBER=52
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-18T00:22:20.257510+00:00
[2023-03-19T13:03:34.529+0000] {dataproc.py:601} INFO - Creating cluster: dataproc-cluster
[2023-03-19T13:03:34.531+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-03-19T13:03:34.532+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-19T13:05:24.202+0000] {dataproc.py:614} INFO - Cluster created.
[2023-03-19T13:05:24.257+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=transform_bq_data, task_id=create_dataproc_cluster, execution_date=20230318T002220, start_date=20230319T130333, end_date=20230319T130524
[2023-03-19T13:05:24.310+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-19T13:05:24.334+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
