[2023-03-21T14:07:48.211+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_masterdag.delete_dataproc_cluster manual__2023-03-21T14:00:00.595190+00:00 [queued]>
[2023-03-21T14:07:48.280+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_masterdag.delete_dataproc_cluster manual__2023-03-21T14:00:00.595190+00:00 [queued]>
[2023-03-21T14:07:48.286+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T14:07:48.287+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-21T14:07:48.287+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T14:07:48.416+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocDeleteClusterOperator): delete_dataproc_cluster> on 2023-03-21 14:00:00.595190+00:00
[2023-03-21T14:07:48.454+0000] {standard_task_runner.py:55} INFO - Started process 39676 to run task
[2023-03-21T14:07:48.486+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_masterdag', 'delete_dataproc_cluster', 'manual__2023-03-21T14:00:00.595190+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/project_master_dags.py', '--cfg-path', '/tmp/tmp405qa7kl']
[2023-03-21T14:07:48.500+0000] {standard_task_runner.py:83} INFO - Job 345: Subtask delete_dataproc_cluster
[2023-03-21T14:07:48.569+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-21T14:07:48.809+0000] {task_command.py:388} INFO - Running <TaskInstance: project_masterdag.delete_dataproc_cluster manual__2023-03-21T14:00:00.595190+00:00 [running]> on host 796cac132c25
[2023-03-21T14:07:49.194+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_masterdag
AIRFLOW_CTX_TASK_ID=delete_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T14:00:00.595190+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T14:00:00.595190+00:00
[2023-03-21T14:07:49.208+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-21T14:07:49.209+0000] {dataproc.py:901} INFO - Deleting cluster: my-dataproc-cluster
[2023-03-21T14:08:26.123+0000] {dataproc.py:871} INFO - Cluster deleted.
[2023-03-21T14:08:26.155+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_masterdag, task_id=delete_dataproc_cluster, execution_date=20230321T140000, start_date=20230321T140748, end_date=20230321T140826
[2023-03-21T14:08:26.219+0000] {local_task_job.py:212} INFO - Task exited with return code 0
