[2023-03-15T22:08:44.384+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task manual__2023-03-15T22:08:42.375851+00:00 [queued]>
[2023-03-15T22:08:44.398+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task manual__2023-03-15T22:08:42.375851+00:00 [queued]>
[2023-03-15T22:08:44.399+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T22:08:44.399+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-15T22:08:44.399+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T22:08:44.422+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2023-03-15 22:08:42.375851+00:00
[2023-03-15T22:08:44.432+0000] {standard_task_runner.py:55} INFO - Started process 16409 to run task
[2023-03-15T22:08:44.441+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-03-15T22:08:42.375851+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/p_download_upload.py', '--cfg-path', '/tmp/tmp1md7l1jt']
[2023-03-15T22:08:44.444+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask download_dataset_task
[2023-03-15T22:08:44.465+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-15T22:08:44.546+0000] {task_command.py:388} INFO - Running <TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task manual__2023-03-15T22:08:42.375851+00:00 [running]> on host 8d6d3f05a6c2
[2023-03-15T22:08:44.659+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T22:08:42.375851+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-15T22:08:42.375851+00:00
[2023-03-15T22:08:44.664+0000] {logging_mixin.py:137} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2023-03-15T22:08:44.667+0000] {logging_mixin.py:137} INFO - file path is /opt/***
[2023-03-15T22:08:44.668+0000] {p_download_upload.py:39} INFO - Downloading files...
[2023-03-15T22:10:13.907+0000] {p_download_upload.py:41} INFO - Downloading completed!
[2023-03-15T22:10:13.910+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-15T22:10:13.926+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230315T220842, start_date=20230315T220844, end_date=20230315T221013
[2023-03-15T22:10:13.987+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-15T22:10:14.035+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
